name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  - master

stages:
- stage: build
  jobs:
  - job: Test_Management_Group_definition_files
    displayName: Test Management Group definition files
    pool:
      name: Hosted Windows 2019 with VS2019
      demands: azureps
    steps:
    - pwsh: |
        Install-Module Pester -Repository PSGallery -force -scope CurrentUser
        Install-Module TestJsonSchema -Repository PSGallery -force -scope CurrentUser
      displayName: 'Install required PowerShell modules'

    - pwsh: |
        Import-Module TestJsonSchema 
        Test-JSONSchema -JsonPath $(Build.SourcesDirectory)\config-files -SchemaPath $(Build.SourcesDirectory)\config-file-schema\input.schema.json -OutputFile $(Build.SourcesDirectory)\TEST-JSONSchema.XML
      errorActionPreference: continue
      displayName: 'Pester Test Azure Management Group configuration file'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/TEST-*.xml'
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: '**\TEST-*.xml'
        failTaskOnFailedTests: true

  - job: Publish_Pattern
    displayName: Publish Pattern
    dependsOn: 
    - Test_Management_Group_definition_files
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
